#cloud-config
users:
  - name: ubuntu
    groups: sudo, docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_public_key}

packages:
  - docker.io
  - docker-compose-plugin

runcmd:
  - systemctl enable docker
  - systemctl start docker
